version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - PORT=5000
      - NODE_EXTRA_CA_CERTS=/app/corp-root-ca.crt
    volumes:
      - ./corp-root-ca.crt:/app/corp-root-ca.crt:ro
      - ./backend/data:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_GRAFANA_BROWSER_URL=${GRAFANA_BROWSER_URL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificate/smc:/etc/nginx/ssl:ro
    restart: always
